Repository codestates-seb/seb39_main_026, pull requests merged in 2022-10, with the labels that each got.

#110 [CHORE] api 요청 코드 정리 및 리액트 쿼리 적용
  client/src/components/DogChoiceModal.tsx
  client/src/components/MainImage.tsx
  client/src/components/Navbar.tsx
  client/src/components/login/LoginModal.tsx
  client/src/components/login/PasswordModal.tsx
  client/src/components/users/PetBirthdaySelector.tsx
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/hooks/FindPasswordquery.ts
  client/src/hooks/LoginQuery.ts
  client/src/hooks/MyDogsListQuery.ts
  client/src/hooks/PetsQuery.ts
  client/src/hooks/SignupQuery.ts
  client/src/hooks/UsersQuery.ts
  client/src/hooks/WalksListQuery.ts
  client/src/hooks/WalksQuery.ts
  client/src/hooks/WriteQuery.ts
  client/src/models/MyPets.ts
  client/src/pages/signup.tsx
  client/src/pages/users/[userId].tsx
  client/src/pages/walks/[walkId]/index.tsx
  client/src/pages/walks/[walkId]/notice.tsx
  client/src/pages/walks/write.tsx
Labels: ⚙️ REFACTOR

#112 [FEAT] 모임 참여하기
  client/src/components/DogChoiceModal.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/hooks/WalksQuery.ts
  client/src/pages/walks/index.tsx
Labels: ✨ 기능 적용, 👉👈 API 연결

#114 [FEAT] 임시 Carousel
  client/src/components/Navbar.tsx
  client/src/components/walks/Carousel.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/components/walks/walksDetail/comment/Comments.tsx
  client/src/pages/signup.tsx
Labels: ✨ 기능 적용, 🌈UI

#124 [FIX] 강아지 정보 수정 시 이미지 관련 버그 처리
  client/src/hooks/PetsQuery.ts
  client/src/pages/login.tsx
Labels: 🛠 버그 수정

#126 [FIX] 모임의 상태 관련 함수 수정
  client/src/components/Layout.tsx
  client/src/components/MoimState.tsx
  client/src/components/MoimStateButton.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/PageNav.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/components/walks/walksDetail/comment/CommentInput.tsx
  client/src/components/walks/walksDetail/comment/Comments.tsx
  client/src/components/walks/walksDetail/notice/MoimNotice.tsx
  client/src/components/walks/wirte/EveryWeekPicker.tsx
  client/src/components/walks/wirte/TitleInput.tsx
Labels: 🌈UI, ⚙️ REFACTOR

#127 [FEAT] 모임 작성 페이지에서 이미지 추가 기능
  client/src/components/login/LoginModal.tsx
  client/src/components/walks/Carousel.tsx
  client/src/components/walks/wirte/ImageUploadZone.tsx
  client/src/hooks/WriteQuery.ts
  client/src/pages/walks/[walkId]/[[...type]].tsx
  client/src/pages/walks/write.tsx
Labels: ✨ 기능 적용, 🌈UI, 👉👈 API 연결

#128 [FEAT] 회원 탈퇴 시 재확인 모달 컴포넌트
  client/src/components/users/DeleteUserButton.tsx
  client/src/components/users/DeleteUserModal.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/users/skeleton/LoadingPets.tsx
  client/src/components/users/skeleton/LoadingUsers.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/pages/users/[userId].tsx
Labels: ✨ 기능 적용, 🌈UI

#131 [FEAT] 404 페이지 생성
  client/src/pages/404.tsx
Labels: ✨ 기능 적용

#132 [FEAT] 모임 작성자의 강아지도 참여 강아지에 포함
  client/src/components/DogChoiceModal.tsx
  client/src/hooks/WriteQuery.ts
  client/src/models/WalksMoim.ts
  client/src/pages/walks/index.tsx
  client/src/pages/walks/write.tsx
Labels: ✨ 기능 적용

#135 [FEAT] 로그인이 필요한 서비스에 로그인 권유 모달 보여주기 및 페이지 접근 관리
  client/src/components/LoginOfferModal.tsx
  client/src/components/login/LoginModal.tsx
  client/src/components/users/LogoutButton.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/comment/CommentInput.tsx
  client/src/components/walks/walksDetail/comment/Comments.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
  client/src/pages/walks/index.tsx
  client/src/pages/walks/write.tsx
Labels: ✨ 기능 적용, 🌈UI

#136 [CHORE] console.log 제거 및 url 정리
  client/src/hooks/CommentQuery.ts
  client/src/hooks/NoticeQuery.ts
  client/src/hooks/PetsQuery.ts
  client/src/hooks/UsersQuery.ts
  client/src/hooks/WalksQuery.ts
  client/src/hooks/WriteQuery.ts
Labels: ⚙️ REFACTOR

#137 [CHORE] 공지사항 모달 컴포넌트 생성
  client/src/components/MainImage.tsx
  client/src/components/NoticeModal.tsx
Labels: 🌈UI

#138 [FIX] 강아지 상세 정보 나이 관련 코드 수정
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/models/UserDogInfo.ts
Labels: 🛠 버그 수정

#139 [FEAT] 메타 태그 오픈 그래프 설정
  client/src/components/TabTitle.tsx
Labels: 📃 문서 정리

#140 [CHORE] 자잘한 css 수정 및 blurDataURL 추가
  client/src/components/login/LoginModal.tsx
  client/src/components/walks/Carousel.tsx
  client/src/components/walks/skeleton/walksDetail/LoadingTitle.tsx
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
Labels: 🌈UI

#141 [CHORE] 소셜 로그인 주석 처리
  client/src/pages/login.tsx
Labels: ⚙️ REFACTOR

#142 [CHORE] navbar 태그 변경 및 로고 링크 해제
  client/src/components/Navbar.tsx
Labels: 🧩 시맨틱

#144 [CHORE] 모집 마감 버튼 CSS 수정
  client/src/components/walks/WalkItem.tsx
Labels: 🌈UI

#148 [FEAT] 참여한 모임인지 구별
  client/src/components/DogChoiceModal.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/notice/NoticeModifyInput.tsx
  client/src/pages/walks/index.tsx
Labels: ✨ 기능 적용, 🌈UI

#152 [CHORE] 스타일 깨진 거 수정
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/comment/CommentInput.tsx
  client/src/pages/walks/index.tsx
Labels: 🌈UI

#153 [CHORE] css 수정 및 탭 이동시 쌓이던 history 문제 해결
  client/src/components/MainImage.tsx
  client/src/components/NavLink.tsx
  client/src/components/Navbar.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
  client/src/components/walks/walksDetail/Introduce.tsx
  client/src/components/walks/walksDetail/PageNav.tsx
  client/src/pages/index.tsx
  client/src/pages/users/[userId].tsx
  client/src/pages/walks/index.tsx
Labels: 🛠 버그 수정, 🌈UI

#155 [CHORE] favicon 적용
  client/public/favicon.ico
  client/src/pages/_document.tsx
  client/src/pages/walks/index.tsx
Labels: 🌈UI

#156 [CHORE] safari css 수정
  client/public/arrow-down.svg
  client/src/components/DogChoiceModal.tsx
  client/src/components/login/LoginModal.tsx
  client/src/components/walks/AddressModal.tsx
  client/src/pages/signup.tsx
  client/src/pages/walks/index.tsx
Labels: 🌈UI
