Repository codestates-seb/seb39_main_026, pull requests merged in 2022-09, with the labels that each got.

#4 [FEAT] index 페이지 레이아웃 세팅 및 mock API fetch
  client/.env
  client/.gitignore
  client/apis/WalksApi.ts
  client/components/Layout.tsx
  client/components/MainImage.tsx
  client/components/Navbar.tsx
  client/components/WalkItem.tsx
  client/components/WalksList.tsx
  client/package.json
  client/pages/index.tsx
  client/public/main_image.jpg
  client/yarn.lock
Labels: good first issue

#6 [CHORE] 데스크탑 CSS 적용
  client/components/Navbar.tsx
  client/components/WalkItem.tsx
  client/components/WalksList.tsx
Labels: enhancement

#8 [FEAT] Walks 데이터 fetch를 위한 react query 적용
  client/apis/WalksApi.ts
  client/apis/api.ts
  client/components/Navbar.tsx
  client/components/WalksList.tsx
  client/components/walks/WalkItem.tsx
  client/components/walks/WalksList.tsx
  client/components/walks/WalksListQuery.ts
  client/models/WalkDefault.ts
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: enhancement

#9 [FIX] 이미지 로드 관련 버그 수정
  client/components/walks/WalksList.tsx
  client/models/WalkDefault.ts
  client/next.config.js
Labels: bug

#18 [FEAT] 주소 선택 컴포넌트 생성
  client/.env
  client/components/walks/AddButton.tsx
  client/components/walks/AddressPicker.tsx
  client/pages/index.tsx
  client/pages/walks/index.tsx
  client/yarn.lock
Labels: enhancement

#20 [FEAT] 주소 선택 모달 구현
  client/components/walks/AddressModal.tsx
  client/components/walks/AddressPicker.tsx
  client/components/walks/WalkItem.tsx
  client/pages/walks/index.tsx
Labels: enhancement

#25 [FEAT] 검색 컴포넌트 생성
  client/components/SearchInput.tsx
  client/components/walks/AddressModal.tsx
  client/components/walks/WalkItem.tsx
  client/pages/walks/index.tsx
Labels: enhancement

#27 [FIX] 검색 컴포넌트 추가
  client/components/SearchInput.tsx
  client/components/walks/AddressModal.tsx
  client/components/walks/WalkItem.tsx
  client/models/WalkDefault.ts
  client/pages/walks/index.tsx
Labels: bug

#29 [ FIX] 주소 입력 관련 버그 수정
  client/components/walks/AddButton.tsx
  client/components/walks/AddressModal.tsx
  client/components/walks/AddressPicker.tsx
  client/components/walks/WalkItem.tsx
  client/components/walks/WalksList.tsx
  client/pages/walks/index.tsx
Labels: enhancement

#35 [FEAT] 유저 페이지 생성 및 api 요청 코드 작성
  client/apis/api.ts
  client/components/Layout.tsx
  client/components/Navbar.tsx
  client/components/users/UsersQuery.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/users/[userId].tsx
  client/pages/users/[username].tsx
  client/states/LoginState.ts
  client/yarn.lock
Labels: enhancement

#42 [FEAT] 모임 정보 sticky Menu
  client/src/components/walks/skeleton/walksDetail/LoadingStickyInfo.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
Labels: 🌈UI

#44 [FEAT] 강아지 정보를 볼 수 있는 모달 적용
  client/.eslintrc.json
  client/public/member/pet/1.json
  client/src/components/CommonButton.tsx
  client/src/components/DogChoiceModal.tsx
  client/src/components/walks/walksDetail/CommentInput.tsx
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/hooks/PetInfoQuery.ts
  client/src/models/UserPetInfo.ts
  client/src/pages/walks/write.tsx
Labels: ✨ 기능 적용, 🌈UI

#46 [FEAT] API 요청 url 변경 및 올바른 변수 적용
  client/src/apis/api.ts
  client/src/components/Navbar.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/users/UsersQuery.ts
  client/src/components/users/WalksInfo.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/Information.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/models/WalkDefault.ts
  client/src/pages/users/[userId].tsx
  client/src/pages/walks/[walkId]/index.tsx
  client/src/pages/walks/[walkId]/notice.tsx
Labels: 👉👈 API 연결

#47 [FEAT] 유저 프로필 수정 권한 관련 상태 생성
  client/src/components/Navbar.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/UserInfo.tsx
  client/src/models/UserDefault.ts
  client/src/pages/users/[userId].tsx
Labels: ✨ 기능 적용

#53 [FIX] 강아지 정보 모달 관련 현상 axios로 임시 해결
  client/src/apis/api.ts
  client/src/components/DogChoiceModal.tsx
  client/src/components/MoimState.tsx
  client/src/components/NavLink.tsx
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/components/walks/walksDetail/Information.tsx
  client/src/components/walks/walksDetail/Introduce.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/hooks/MyDogsListQuery.ts
  client/src/hooks/MyPetsListQuery.ts
  client/src/hooks/PetInfoQuery.ts
  client/src/hooks/WalksDetailQuery.ts
  client/src/models/UserDogInfo.ts
  client/src/models/WalkDefault.ts
  client/src/pages/walks/[walkId]/index.tsx
Labels: 🛠 버그 수정, ✨ 기능 적용, 🌈UI, 👉👈 API 연결

#57 [FEAT] 강아지 정보 수정 오버레이 생성
  client/src/components/Layout.tsx
  client/src/components/Navbar.tsx
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/SelectButton.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/models/MyPets.ts
  client/src/pages/users/[userId].tsx
Labels: ✨ 기능 적용, 🌈UI

#59 [FEAT] 로그인 페이지
  client/src/components/login/LoginButton.tsx
  client/src/pages/login.tsx
Labels: 🌈UI

#60 [FEAT] 마이페이지 강아지 정보 수정
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/PetPersonalityButton.tsx
  client/src/components/users/SelectButton.tsx
  client/src/components/users/UsersQuery.ts
  client/src/models/MyPets.ts
  client/src/models/UserDefault.ts
Labels: ✨ 기능 적용, 🌈UI

#63 [FEAT] 임시 로그인 기능 구현
  client/src/apis/api.ts
  client/src/components/login/LoginModal.tsx
  client/src/hooks/LoginQuery.ts
  client/src/models/UserLogin.ts
  client/src/pages/login.tsx
  client/src/states/UserState.ts
Labels: ✨ 기능 적용, 🌈UI, 👉👈 API 연결

#64 [FEAT] 강아지 생일 selector 구현
  client/package.json
  client/src/components/login/LoginModal.tsx
  client/src/components/users/PetBirthdaySelector.tsx
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/PetPersonalityButton.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/users/UsersQuery.ts
  client/src/models/MyPets.ts
  client/src/models/UserDefault.ts
  client/src/pages/users/[userId].tsx
  client/yarn.lock
Labels: ✨ 기능 적용, 🌈UI

#67 [FEAT] 회원가입 페이지
  client/src/apis/api.ts
  client/src/components/ResionPick.tsx
  client/src/hooks/SignupQuery.ts
  client/src/models/UserSingup.ts
  client/src/pages/signup.tsx
Labels: ✨ 기능 적용, 🌈UI, 👉👈 API 연결

#68 [CHORE] 오타 수정 및 누락된 스타일 추가
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/hooks/SignupQuery.ts
  client/src/models/UserSignup.ts
  client/src/pages/signup.tsx
Labels: 👀 오타수정

#65 [CHORE] 올바른 headings 적용
  client/src/components/MainImage.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/models/WalkDefault.ts
  client/src/pages/walks/index.tsx
Labels: 🧩 시맨틱

#72 [REFACTOR] 회원가입 페이지 리팩토링
  client/src/components/RegionPick.tsx
  client/src/components/ResionPick.tsx
  client/src/components/login/LoginModal.tsx
  client/src/hooks/LoginQuery.ts
  client/src/models/UserDefault.ts
  client/src/models/UserInfo.ts
  client/src/models/UserSignup.ts
  client/src/pages/signup.tsx
Labels: ⚙️ REFACTOR

#74 [FEAT] 유저네임 변경 요청
  client/src/components/users/UserInfo.tsx
  client/src/components/walks/WalksList.tsx
Labels: 🛠 버그 수정, ✨ 기능 적용, 👉👈 API 연결

#76 [REFACTOR] 강아지 선택 모달
  client/src/apis/api.ts
  client/src/components/DogChoiceModal.tsx
  client/src/components/RegionPick.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/hooks/MyDogsListQuery.ts
  client/src/models/UserDefault.ts
  client/src/models/UserInfo.ts
  client/src/pages/walks/index.tsx
  client/src/states/UserState.ts
Labels: ⚙️ REFACTOR

#77 [FEAT] 마이페이지 로그아웃 기능 구현
  client/src/components/users/LogoutButton.tsx
  client/src/components/users/UserInfo.tsx
  client/src/pages/users/[userId].tsx
  client/src/pages/walks/index.tsx
Labels: ✨ 기능 적용, 🌈UI

#78 [FEAT] 마이페이지 유저 이미지 업로드
  client/src/components/Navbar.tsx
  client/src/components/SearchInput.tsx
  client/src/components/users/LogoutButton.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
  client/src/components/walks/WalksListQuery.ts
  client/src/pages/index.tsx
  client/src/pages/walks/index.tsx
Labels: ✨ 기능 적용, 🌈UI

#80 [FEAT] 모임 공지사항 API 연결
  client/src/components/CommonButton.tsx
  client/src/components/walks/walksDetail/MoimNotice.tsx
  client/src/pages/walks/[walkId]/notice.tsx
Labels: 🌈UI, 👉👈 API 연결

#81 [FEAT] 산책 리스트에 주소 적용 및 검색 기능 구현
  client/src/components/SearchInput.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/walks/AddressModal.tsx
  client/src/components/walks/AddressPicker.tsx
  client/src/components/walks/WalksList.tsx
  client/src/components/walks/WalksListQuery.ts
  client/src/pages/index.tsx
  client/src/pages/walks/index.tsx
Labels: 🛠 버그 수정, ✨ 기능 적용, 👉👈 API 연결

#82 [FEAT] 회원가입 후 로그인 처리
  client/src/models/UserSignup.ts
  client/src/pages/signup.tsx
Labels: ✨ 기능 적용

#83 [FEAT] 댓글 추가
  client/src/apis/api.ts
  client/src/components/walks/walksDetail/CommentInput.tsx
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/hooks/CommentQuery.ts
  client/src/models/UserDogInfo.ts
  client/src/models/WalkDefault.ts
Labels: ✨ 기능 적용

#85 [FEAT] 강아지 등록 기능 구현
  client/src/components/users/PetBirthdaySelector.tsx
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetInfo.tsx
Labels: 🛠 버그 수정, ✨ 기능 적용, 👉👈 API 연결

#86 [FEAT] 모임 디테일 페이지 자잘한 수정
  client/public/main_image.jpg
  client/public/member/pet/1.json
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/hooks/Sroll.ts
Labels: ✨ 기능 적용, 🌈UI

#91 [FEAT] 모임 등록
  client/src/apis/api.ts
  client/src/components/DogChoiceModal.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/wirte/PlaceInput.tsx
  client/src/components/walks/wirte/TitleInput.tsx
  client/src/hooks/AddMoimQuery.ts
  client/src/hooks/Scroll.ts
  client/src/hooks/WalksDetailQuery.ts
  client/src/models/WalkDefault.ts
  client/src/models/WalksMoim.ts
  client/src/pages/walks/write.tsx
Labels: 🛠 버그 수정, ✨ 기능 적용, 🌈UI

#92 [FEAT] 배포 스크립트 수정
  client/scripts/deploy.sh
Labels: 🛠 버그 수정

#93 [FEAT] 이미지 처리 관련 로직 변경
  client/next.config.js
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
  client/src/hooks/UsersQuery.ts
  client/src/pages/users/[userId].tsx
Labels: ✨ 기능 적용

#95 [FIX] 작업 복구
  client/src/apis/api.ts
  client/src/components/CommonButton.tsx
  client/src/components/Navbar.tsx
  client/src/components/SearchInput.tsx
  client/src/components/users/PetBirthdaySelector.tsx
  client/src/components/users/PetEditOverlay.tsx
  client/src/components/walks/AddressModal.tsx
  client/src/components/walks/AddressPicker.tsx
  client/src/components/walks/WalksListQuery.ts
  client/src/components/walks/walksDetail/CommentInput.tsx
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/components/walks/walksDetail/MoimNotice.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/hooks/CommentQuery.ts
  client/src/hooks/LoginQuery.ts
  client/src/hooks/SignupQuery.ts
  client/src/models/UserDogInfo.ts
  client/src/models/UserSignup.ts
  client/src/pages/index.tsx
  client/src/pages/signup.tsx
  client/src/pages/walks/[walkId]/notice.tsx
  client/src/pages/walks/index.tsx
Labels: 🛠 버그 수정

#96 [CHORE] 이미지 관련 자잘한 수정 및 검색 쿼리 변경
  client/src/components/DogChoiceModal.tsx
  client/src/components/SearchInput.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
Labels: 🛠 버그 수정, 🌈UI

#99 [FEAT] 댓글 수정/삭제
  client/src/apis/api.ts
  client/src/components/Layout.tsx
  client/src/components/walks/walksDetail/Comments.tsx
  client/src/components/walks/walksDetail/DetailLayout.tsx
  client/src/components/walks/walksDetail/comment/ComentModifyInput.tsx
  client/src/components/walks/walksDetail/comment/CommentInput.tsx
  client/src/components/walks/walksDetail/comment/CommentMenu.tsx
  client/src/components/walks/walksDetail/comment/Comments.tsx
  client/src/hooks/CommentQuery.ts
  client/src/models/WalkDefault.ts
Labels: ✨ 기능 적용, 🌈UI, 👉👈 API 연결

#102 [CHORE] imgUrl 변경 및 리액트 쿼리 적용
  client/src/components/Navbar.tsx
  client/src/components/users/PetBirthdaySelector.tsx
  client/src/components/users/PetEditInfo.tsx
  client/src/components/users/PetInfo.tsx
  client/src/components/users/UserInfo.tsx
  client/src/components/walks/WalkItem.tsx
  client/src/components/walks/WalksList.tsx
  client/src/components/walks/WalksListQuery.ts
  client/src/components/walks/walksDetail/DogInfoModal.tsx
  client/src/components/walks/walksDetail/ParticipantsInfo.tsx
  client/src/components/walks/walksDetail/StickyInfo.tsx
  client/src/components/walks/walksDetail/Title.tsx
  client/src/components/walks/walksDetail/comment/Comments.tsx
  client/src/hooks/PetsQuery.ts
  client/src/hooks/UsersQuery.ts
  client/src/hooks/WalksListQuery.ts
  client/src/models/MyPets.ts
  client/src/models/UserDefault.ts
  client/src/pages/index.tsx
  client/src/pages/users/[userId].tsx
Labels: 🛠 버그 수정, 👉👈 API 연결

#104 [FEAT] 모임 공지사항 등록/수정/삭제
  client/src/components/CommonButton.tsx
  client/src/components/login/LoginModal.tsx
  client/src/components/walks/walksDetail/MoimNotice.tsx
  client/src/components/walks/walksDetail/comment/CommentInput.tsx
  client/src/components/walks/walksDetail/comment/Comments.tsx
  client/src/components/walks/walksDetail/notice/MoimNotice.tsx
  client/src/components/walks/walksDetail/notice/NoticeModifyInput.tsx
  client/src/hooks/NoticeQuery.ts
  client/src/models/WalkDefault.ts
  client/src/pages/signup.tsx
  client/src/pages/walks/[walkId]/notice.tsx
Labels: ✨ 기능 적용, 🌈UI, 👉👈 API 연결

#106 [FEAT] 비밀번호 찾기 기능 구현
  client/src/components/login/PasswordModal.tsx
  client/src/components/users/PetEditInfo.tsx
  client/src/hooks/FindPasswordquery.ts
  client/src/pages/login.tsx
Labels: ✨ 기능 적용, 🌈UI

#107 [FEAT] 회원 탈퇴 기능 구현
  client/src/components/users/DeleteUserButton.tsx
  client/src/hooks/UsersQuery.ts
  client/src/pages/users/[userId].tsx
Labels: ✨ 기능 적용

#109 [FEAT] write 페이지에서 이미지 추가하기(1/2)
  client/src/hooks/AddMoimQuery.ts
  client/src/pages/walks/write.tsx
Labels: 👉👈 API 연결
